@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title Идеи от Сергея Коваленко

* доклад в форме \n лайф-кодинга
** проект в гитхабе
*** многопользовательский режим
*** версионирование
*** доступность
*** документация рядом с кодом
** диаграмма \n самого доклада \n рекурсия
** эволюция: \n картинки-> код \n код-> картинки
*** исполняемый код
** фишки
*** автонумерация
*** переменные
** документация \n как часть приложения
*** документация отображается \n пользователю, саппорту
*** паспорт системы
*** перевод на другие языки

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
