@startuml
'https://plantuml.com/sequence-diagram
mainframe **GEO GET /api/v1/geopoligons**
'!includesub poligons_api.puml !VARIABLES
'!includesub poligons_api.puml !ACTORS
'!includesub poligons_api.puml !POLIGONS_REQUEST
'!includesub poligons_api.puml !POLIGONS_RESPONSE_200
'!includesub poligons_api.puml !POLIGONS_RESPONSE_EMPTY
'!includesub poligons_api.puml !POLIGONS_RESPONSE_UNAUTHORIZED
'!includesub poligons_api.puml !POLIGONS_RESPONSE_BAD_REQUEST
'!includesub poligons_api.puml !POLIGONS_RESPONSE_INTERNAL_ERROR

!startsub VARIABLES
!$GREEN = "#TECHNOLOGY"
!$PINK = "#IMPLEMENTATION"
!$POLIGONS_NAME = "GET geopoligons"
!$GEO_REQUEST = "GET /api/v1/geopolygons?lat=56.337532&lng=43.963482"
!$POLIGONS_LINK = "https://space.geookat.ru/pages/viewpage.action?pageId=3937654929"
!$END_GEO = "end.lat, end.lon"
!endsub

skinparam MaxMessageSize 300
skinparam WrapWidth 350
skinparam FontSize 8

autonumber 0 5

!startsub ACTORS
participant geolocator as geo
!endsub

!startsub POLIGONS_REQUEST
[-> geo: [[$$POLIGONS_LINK request $POLIGONS_NAME]] ($END_GEO)
note left geo
комментарий к **%autonumber%**
$$POLIGONS_LINK
$GEO_REQUEST
end note
activate geo
!endsub

!startsub POLIGONS_RESPONSE_200
alt $GREEN позитивный сценарий
 return array<poligon_id>, 200
note right geo
комментарий к **%autonumber%**
{ "value": {
  "geopolygonIds": [
   { "id": "3a300c4f-9c9d-46d0-8a7c-18114d55e53d"},
   { "id": "8e283a1c-906c-4604-96ca-237c0d56635d"}
  ]}}
end note
!endsub

!startsub POLIGONS_RESPONSE_EMPTY
else $PINK Не найден ни один геополигон
 [<-- geo: return: error_message, 200
 note right geo
 комментарий к **%autonumber%**
 {     "value": {
         "geopolygonIds": []     } }
 end note
 !endsub

 !startsub POLIGONS_RESPONSE_UNAUTHORIZED
else $PINK Авторизационный токен невалиден или отсутствует
 [<-- geo: return: error_message, 200
 note right geo
 комментарий к **%autonumber%**
 {     "error": {
         "code": "401";
         "message": "Unauthorized"     } }
 end note
!endsub

!startsub POLIGONS_RESPONSE_BAD_REQUEST

else $PINK Ошибка при десериализации запроса
 [<-- geo: return: error_message, 200
 note right geo
 комментарий к **%autonumber%**
 {     "error": {
         "code": "BAD_REQUEST";
         "message": "Bad request"     } }
 end note
!endsub

!startsub POLIGONS_RESPONSE_INTERNAL_ERROR
 else $PINK Внутренняя ошибка сервиса
 [<-- geo: return: error_message, 200
 note right geo
 комментарий к **%autonumber%**
 {     "error": {
         "code": "INTERNAL_SERVER_ERROR";
         "message": "Internal server error"     } }
 end note
!endsub
end
deactivate geo


@enduml