@startmindmap
'https://plantuml.com/mindmap-diagram
!$E = "\n "
caption figure 1
title My super title

* вопросы
** 1. пришли - что я вам дам
*** расскажу о PlantUML - швейцарском ноже аналитика
*** покажу как создать sequence-диаграмму
*** покажу лайфхаки, облегчающие работу
**** переменные

** где применимо, а где нет
*** +
**** описание взаимодействия $E НЕСКОЛЬКИХ объектов - sequence
**** описание алгоритмов (job) - activity
**** всего - mindMap
**** визуализация воркфлоу - диаграмма Ганта
*** - описание логической модели базы данных

** что дает нам $E применение данного инструмента
*** два способа отображения решения (текст-код и картинка)
*** PlantUML + IDE + git = версионирование, совместная работа, ревью, документация - часть приложения
*** знакомство с основами программирования

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
