@startmindmap
'https://plantuml.com/mindmap-diagram
skinparam wrapWidth 700

caption figure 1
title Документирование интеграций в виде sequence-диаграмм при помощи PlantUML

* доклад
** вступление
*** Когда я прошлым летом на конференции NextWayConf рассказывала о пользе визуала в технической документации, о том что картинки обрабатываются мозгом в десятки тысяч раз быстрее, чем текст, о том, как важно, чтобы документация радовала своей доступностью и легкостью восприятия, а не наводила простынками текста тоску и уныние на своих потребителей, я демонстрировала различия в текстовом и визуальном описании процесса на draw.io, и в тот момент это был мой любимый инструмент. И вот после доклада прозвучал вопрос: "А почему draw.io, а не PlantUML? Ведь в нем гораздо легче актуализировать схему". Не помню уже, что я тогда ответила и как агрументировала свой выбор, но зерно сомнения было заронено.
***  Через некоторое время, в очередной раз внося изменения в свою draw.io-диаграмму, а вы представляете этот процесс - сместить элементы, в необходимых поправить содержимое, и все это ручками... Я решила попробовать, а как это будет с Plantom. Поскольку установленная Intelligy Idea с бытности меня автотестировщиком, я легко нашла нужны plugin, открыла мануал, и попробовала воспроизвести свою картинку в Plante. Получилось визуально так себе, но информативность не пострадала. Вставила я диаграмму в Confluence, показала задачу команде и на этом успокоилась и вернулась к draw.io. Но когда мне потребовалось обновить плантовскую схему я сделала это одним CTRL+R, меня проняло.
*** Я завела свой проект в Gitlab рядом с проектами своих разрабов и отныне творила только там, параллельно изучая возможности инструмента, "золотая лихорадка" поиска фич и трюков еще не прошла, но некоторые найденные плюшки я вам покажу.
** 1. o PlantUML
***: <img:http://plantuml.com/logo3.png>
        ;
*** [[https://plantuml.com/ru/ документация]]
*** Арно Рокес: "поддержание документации в актуальном состоянии"
*** какой инструмент используете для построения диаграмм?
** 2. обогащаем sequence
'** 3. обзор аналогов
'*** Mermaid - написан на JavaScript
'****: <img:vscode.png>
';
'*** PlantUML - написан на Java
'****: <img:idea.png>
';
'****: <img:vscode.png>
';


** достоинства
*** большое количество видов диаграмм
*** большое количество интеграций (Confluence, plugins к IDE )
*** подключаемые библиотеки

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
