@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title Документирование интеграций в виде sequence-диаграмм при помощи PlantUML

* доклад
** 1. o PlantUML
***: <img:http://plantuml.com/logo3.png>
        ;
*** [[https://plantuml.com/ru/ документация]]
*** Арно Рокес: "поддержание документации в актуальном состоянии"
*** какой инструмент используете для построения диаграмм?
** 2. обогащаем sequence
*** добавляем переменные
*** добавляем ссылки

*** кастомизируем изображение [[https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html#note All Skin Parameters]]
** 3. обзор аналогов
*** Mermaid - написан на JavaScript
****: <img:vscode.png>
;
*** PlantUML - написан на Java
****: <img:idea.png>
;
****: <ref:idea.png>
;


*** достоинства
**** большое количество видов диаграмм
**** большое количество интеграций (Confluence, plugins к IDE )
*** <s>Raspyfi</s> => Volumio

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
