@startuml
'https://plantuml.com/sequence-diagram
autonumber
!include /resources/skinparams.puml
!includesub /resources/variables.puml !VARIABLES
!includesub poligons_api.puml !VARIABLES

box "Internal Service" #STRATEGY

participant api_gateway as gw
participant strategy as strategy
database strategy_db as DB
participant routes_map as rm
end box




gw -> strategy: [[$DELIVERY_ROUTE_LINK request POST $DELIVERY_ROUTE_NAME]]
note left strategy #aqua
заметка к **%autonumber%**
{
  "start": {
    "objectId": "msk"
  },
  "end": {
    "kladr": "78",
    "lat": 59.93123,
    "lon": 30.31123
  },
  "deliveryMethod": "посылка"
}
end note
activate strategy
strategy->strategy: проверить запрос (обязательны  start.objectId, end.lat, end.lon, deliveryMethod)
'includesub poligons_api.puml !ACTORS
!includesub poligons_api.puml !POLIGONS_REQUEST

!includesub poligons_api.puml !POLIGONS_RESPONSE_200
strategy-> DB: SELECT (array<poligon_id>,  deliveryMethod)
note right DB
<img /resources/tables.png {scale=0.5}>
end note
activate DB
DB-->strategy: return: object_id_end with MIN(priority)
deactivate DB
strategy->rm: [[$ROUTE_LINK request $ROUTE_NAME ]]
note left rm #coral
заметка к **%autonumber%**
{
  "objectIdStart": "msk",
  "objectIdEnd": "spb"
}
end note
note right rm #coral
заметка к **%autonumber%**
{
  "route": [
    {
      "stepNum": 1,
      "code": 1234,
      "objectIdEnd": "spb",
      "objectEndType": "DISTRIBUTION_CENTER",
      "duration": 720
    }
  ]
}
end note

activate rm
rm-->strategy: return: route
deactivate rm
alt #TECHNOLOGY маршрут возвращен
strategy->strategy: взять route  преобразовать ответ к шаблону
note right strategy #aqua
заметка к **%autonumber%**
{
  "route": [
    {
      "code": 1234,
      "stepNumber": 1,
      "logObjectStart": "msk",
      "logObjectEnd": "spb",
      "controlDeliverytime": 720
    }
  ]
}
end note
strategy --> gw:  response $DELIVERY_ROUTE_NAME  ответ 200
else %lighten(IMPLEMENTATION, 5) маршрут не найден
strategy --> gw:  response $DELIVERY_ROUTE_NAME  404 "Not Found"
note right strategy #aqua
заметка к **%autonumber%**
{
  "error": "ROUTE_NOT_FOUND"
}
end note
end

!includesub poligons_api.puml !POLIGONS_RESPONSE_EMPTY
strategy --> gw: return: error_message, 200
note right strategy
 комментарий к **%autonumber%**
 {
   "error": {
     "code": "GEO_SERVICE_ERROR",
     "details": "geopolygons not found"
   }
 }
 end note
!includesub poligons_api.puml !POLIGONS_RESPONSE_UNAUTHORIZED
 strategy --> gw: return: error_message, 200
 note right strategy
  комментарий к **%autonumber%**
  {
    "error": {
      "code": "GEO_SERVICE_ERROR",
      "details": "401:Unauthorized"
    }
  }
  end note

!includesub poligons_api.puml !POLIGONS_RESPONSE_BAD_REQUEST
strategy --> gw: return: error_message, 200
  note right strategy
   комментарий к **%autonumber%**
    {
      "error": {
        "code": "GEO_SERVICE_ERROR",
        "details": "Bad request"
      }
    }
   end note
!includesub poligons_api.puml !POLIGONS_RESPONSE_INTERNAL_ERROR
  strategy --> gw: return: error_message, 200
 note right strategy
   комментарий к **%autonumber%**
   {
     "error": {
       "code": "GEO_SERVICE_ERROR",
       "details": "Internal server error"
     }
   }
end note
end

deactivate strategy
@enduml