@startmindmap
'https://plantuml.com/mindmap-diagram
!$E = "\n"
title Ответы на 3 вопроса от Ольги

* вопросы
** пришли - что я вам дам?
*** расскажу о PlantUML, $E как универсальном инструменте $E построения диаграмм
*** вместе с вами создам sequence-диаграмму
*** поделюсь плюшками от программирования
**** автонумерация
**** переменные
**** работа с json

**  где применимо, где нет?
*** +
**** **sequence** - отображение интеграций
**** **активити** - блок-схемы для визуализации $E логики "под капотом"
**** **ERD** - отображение физической модели данных (таблицы)
**** **MindMap** - для ... всякого-разного (рассуждений)
*** -
**** более высокий порог входа (IDE, начатки программирования, git)

** что использование подобного $E инструмента нам дает?
*** повышение качества проектирования $E за счет использования формального языка программирования
*** общий контекст с разработкой
*** решение представлено в двух формах (код и картинка)
*** шаг в направлении "doc as code"
*** бонусы git (совместная работа, версионирование)
*** у PlantUML отличная документация с примерами кода


@endmindmap
